### PR TITLE
Remove routine renames from mpas_ocn_okubo_weiss.F90

### PR DESCRIPTION
**Pull request by gdicker1**
This PR removes unneeded renaming of module-specific qsort routines to dummy*. Since those qsort routines aren't used in mpas_ocn_okubo_weiss anymore, they don't need to be renamed.

Also removes a duplicate of mpas_ocn_okubo_weiss.F90

### CODE REVIEW

**Comment by gdicker1** [comment]
@dazlich, did I explain this correctly? I don't see any reason to not move this through!

**Comment by dazlich** [comment]
That’s a good description. I think it broke when the atm framework changed. I think in the future we will want to consolidate to one framework.

Sent from my iPhone

On Apr 27, 2023, at 9:30 PM, gdicker1 ***@***.***> wrote:

﻿

** Caution: EXTERNAL Sender **

@dazlich<https://github.com/dazlich>, did I explain this correctly? I don't see any reason to not move this through!

**Review by dazlich — APPROVED** [review]
Looks good to me, thanks

**Review by sherimickelson — APPROVED** [review]
Thanks, @gdicker1 .  Looks good.

**Review by gdicker1 — COMMENTED** [review]
From recent looks at the code, I think we can merge this. There aren't any qsort routines left in the framework that I can find, so these renames aren't doing anything.

(Merge or don't merge have the same functionality, but merging would be cleaner in my opinion.)

**Pull request merged**
